export default {
  isbn10: null,
  isbn13: null,
  title: null,
  description: null,
  coverImage: null,
  format: null,
  language: null,
  authors: null,
  publishers: null,
  edition: null,
  pages: null,
  publishYear: null,
  publishDate: null,
  private: null,
  stars: null,
  type: null,
  subtypes: null,
  keywords: null,
  owner: null,
  ownersReview: null
}