export default {
  TYPE: [
    'FICTION',
    'NON-FICTION'
  ],
  FICTION: [
    "Action and adventure",
    "Alternate history",
    "Anthology",
    "Chick lit",
    "Children's",
    "Classic",
    "Comic book",
    "Coming-of-age",
    "Crime",
    "Drama",
    "Fairytale",
    "Fantasy",
    "Graphic novel",
    "Historical fiction",
    "Horror",
    "Mystery",
    "Paranormal romance",
    "Picture book",
    "Poetry",
    "Political thriller",
    "Romance",
    "Satire",
    "Science fiction",
    "Short story",
    "Suspense",
    "Thriller",
    "Western",
    "Young adult"
  ],
  NON_FICTION: [
    "Art/architecture",
    "Autobiography",
    "Biography",
    "Business/economics",
    "Crafts/hobbies",
    "Cookbook",
    "Diary",
    "Dictionary",
    "Encyclopedia",
    "Guide",
    "Health/fitness",
    "History",
    "Home and garden",
    "Humor",
    "Journal",
    "Math",
    "Memoir",
    "Philosophy",
    "Prayer",
    "Religion, spirituality, and new age",
    "Textbook",
    "True crime",
    "Review",
    "Science",
    "Self help",
    "Sports and leisure",
    "Travel",
    "True crime"
  ],
  LANGUAGE: [
    'Portuguese',
    'English',
    'Spanish',
    'French',
    'German',
    'Italian',
    'Russian',
    'Dutch',
    'Chinese',
    'Japanese',
    'Korean',
    'Hindi',
    'Arab',
    'Hebrew',
    'Latin',
    'Greek',
    'Ancient Greek'
  ],
  FORMAT: [
    'Paperback',
    'Hard Case Wrap',
    'Hard Case Dust Jacket',
    'e-Book'
  ],
  SORT_KEYS: {
    BOOKS: [
      'title',
      'format',
      'language',
      'publishYear',
      'publishDate',
      'private',
      'stars'
    ],
    AUTHORS: [
      'name',
      'birthDate',
      'deathDate',
      'birthPlace',
      'deathPlace'
    ],
    PUBLISHERS: [
      'name',
      'country',
      'city'
    ]
  }
}
